#!/bin/bash

# Function to detect the Linux distribution
get_distro() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        echo $ID
    elif [ -f /etc/debian_version ]; then
        echo "debian"
    elif [ -f /etc/arch-release ]; then
        echo "arch"
    elif [ -f /etc/rocky-release ]; then
        echo "rocky"
    else
        echo "unknown"
    fi
}

# Detect the distribution
DISTRO=$(get_distro)
# Function to install packages based on the distribution
install_packages() {
    case $DISTRO in
        debian|ubuntu)
            sudo apt install "$@"
            ;;
        arch)
            sudo pacman -S --needed "$@"
            ;;
        rocky|fedora)
            sudo dnf install "$@"
            ;;
        *)
            echo "Unsupported distribution. Please install the following packages manually: $@"
            read -p "Press Enter to continue or Ctrl+C to exit..."
            ;;
    esac
}

# Check whether this system is a laptop (has a battery)
is_laptop() {
    ls /sys/class/power_supply/BAT* > /dev/null 2>&1
}

current_dir=$(pwd)

echo "Installing and setting up dwm-curado..."
echo "Installing dependencies"
case $DISTRO in
    debian|ubuntu)
        install_packages libx11-dev libxft-dev libimlib2-dev libxinerama-dev libxcb-res0-dev kitty feh \
        mate-polkit flameshot dunst libconfig-dev libdbus-1-dev libegl-dev libev-dev libgl-dev libepoxy-dev \
        libpcre2-dev libpixman-1-dev libx11-xcb-dev libxcb1-dev libxcb-composite0-dev libxcb-damage0-dev \
        libxcb-dpms0-dev libxcb-glx0-dev libxcb-image0-dev libxcb-present-dev libxcb-randr0-dev libxcb-render0-dev \
        libxcb-render-util0-dev libxcb-shape0-dev libxcb-util-dev libxcb-xfixes0-dev libxext-dev meson ninja-build \
        uthash-dev cmake alsa-utils rofi
        ;;
    arch)
        install_packages libx11 libxft libxinerama libxcb kitty feh mate-polkit flameshot dunst base-devel \
        libconfig dbus libev libxext libgl libegl libepoxy meson pcre2 pixman uthash xcb-util-image \
        xcb-util-renderutil xorgproto cmake imlib2 xcb-util xorg-xev xorg-xbacklight \
        alsa-utils thunar-media-tags-plugin thunar-archive-plugin thunar-volman rofi
        ;;
    rocky|fedora)
        install_packages libX11-devel libXft-devel imlib2-devel libXinerama-devel libxcb-devel kitty feh mate-polkit \
        flameshot dunst dbus-devel gcc git libconfig-devel libdrm-devel libev-devel libX11-xcb \
        libXext-devel libGL-devel libEGL-devel libepoxy-devel meson ninja-build pcre2-devel \
        pixman-devel uthash-devel xcb-util-image-devel xcb-util-renderutil-devel xorg-x11-proto-devel \
        xcb-util-devel cmake alsa-utils rofi
        ;;
esac

# Laptop-only extras: brightness control tool and key bindings
if is_laptop; then
    echo "Laptop detected. Installing brightnessctl and adding brightness controls to DWM config."

    install_packages brightnessctl

    # Append new key bindings to config.def.h (only once)
    if ! grep -q "brightnessctl" config.def.h; then
        sed -i '/{ MODKEY,                       XK_e,          spawn,                  SHCMD ("thunar")}, \/\/ open thunar file manager/a \
    { 0,                            0x1008ff03,    spawn,                  SHCMD ("brightnessctl s 10%-")}, // decrease backlight brightness\
    { 0,                            0x1008ff02,    spawn,                  SHCMD ("brightnessctl s +10%")}, // increase backlight brightness\
    { 0,                            0x1008ff8e,    spawn,                  SHCMD ("brightnessctl s 10%-")}, // decrease backlight brightness' config.def.h

        echo "Brightness controls added to DWM config."
    else
        echo "Brightness controls already present in DWM config."
    fi
else
    echo "This doesn't appear to be a laptop. Skipping brightness control configuration."
fi

# Recompile and reinstall DWM
sudo make clean install

get_git_path() {
    # Check if GIT_PATH is already set
    if [ -z "$GIT_PATH" ]; then
        read -p "Enter the path for git repositories (default: $HOME/git): " git_path
        GIT_PATH=${git_path:-$HOME/git}
        export GIT_PATH

        if [ ! -d "$GIT_PATH" ]; then
            mkdir -p "$GIT_PATH"
            echo "Created git directory at $GIT_PATH"
        else
            echo "Git directory already exists at $GIT_PATH"
        fi
    else
        echo "GIT_PATH is already set to $GIT_PATH"
    fi
}

# Ask user if they want to install and setup slstatus-curado
read -p "Do you want to install and setup slstatus-curado, a fork of slstatus? (y/n) " install_slstatus_curado

if [[ $install_slstatus_curado =~ ^[Yy]$ ]]; then
    get_git_path
    git clone https://github.com/curadotd/slstatus-curado.git $GIT_PATH/slstatus-curado
    cd $GIT_PATH/slstatus-curado
    ./setup
else
    echo "Skipping slstatus-curado installation and setup."
fi

cd $current_dir

# Ask user if they want to install picom (FT-Labs fork, provides blur/rounding/animations)
read -p "Do you want to install picom? (y/n) " install_picom

if [[ $install_picom =~ ^[Yy]$ ]]; then
    echo "Installing picom..."

    # Check if picom exists
    if ! command -v picom &> /dev/null; then
        get_git_path
        if [ ! -d $GIT_PATH/picom ]; then
            if ! git clone https://github.com/FT-Labs/picom.git $GIT_PATH/picom; then
                echo "Failed to clone the repository"
                exit 1
            fi
        else
            echo "Repository already exists, skipping clone"
        fi
        cd $GIT_PATH/picom || { echo "Failed to change directory to picom"; exit 1; }

        case $DISTRO in
            debian|ubuntu)
                install_packages libev-dev libxcb-present-dev
                ;;
            arch)
                install_packages libev libxcb xcb-util-renderutil xcb-util-image
                ;;
            rocky|fedora)
                install_packages libev-devel libxcb-devel xcb-util-renderutil-devel xcb-util-image-devel
                ;;
            *)
                echo "This system is not supported. Please install the required dependencies manually."
                echo "Required packages: libev, libxcb, xcb-util-renderutil, xcb-util-image"
                read -p "Press Enter to continue or Ctrl+C to exit..."
                ;;
        esac

        # Build the project
        if ! meson setup --buildtype=release build; then
            echo "Meson setup failed"
            exit 1
        fi
        if ! ninja -C build; then
            echo "Ninja build failed"
            exit 1
        fi
        # Install the built binary
        if ! sudo ninja -C build install; then
            echo "Failed to install the built binary"
            exit 1
        fi
        echo "Picom (FT-Labs) installed successfully"
        echo "The macOS Tahoe glass settings live in ~/.config/picom/picom.conf (from the dotconfig repo)."
        cd $current_dir
    else
        echo "picom is already installed"
        cd $current_dir
    fi
else
    echo "Skipping picom install."
    cd $current_dir
fi

# Ask user if they want to install LightDM greeter
read -p "Do you want to install and enable LightDM greeter? (y/n) " install_lightdm

if [[ $install_lightdm =~ ^[Yy]$ ]]; then
    echo "Installing LightDM and LightDM GTK greeter..."
    case $DISTRO in
        debian|ubuntu)
            install_packages lightdm lightdm-gtk-greeter
            sudo dpkg-reconfigure lightdm
            ;;
        arch)
            install_packages lightdm lightdm-gtk-greeter
            sudo systemctl enable lightdm
            ;;
        rocky|fedora)
            install_packages lightdm lightdm-gtk
            sudo systemctl enable lightdm
            sudo systemctl set-default graphical.target
            ;;
    esac
    echo "LightDM has been installed and enabled."
else
    echo "Skipping LightDM installation."
fi

echo "DWM setup complete."
